config/routes.rb
Rails.application.routes.draw do
  resources :instances
  resources :zipcodes
  resources :store_adds
  resources :routes
  resources :holds
  resources :customer_adds
  resources :carries
  resources :couriers
  resources :delivers
  resources :packages
  resources :customers
  resources :stores
  devise_for :users
  devise_scope :user do
    authenticated :user do
       root :to => 'customers#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'delivery#homepage', as: :unauthenticated_root
    end
  end
  resources :advisors
  post 'delivery/Tracking'
  get 'delivery/homepage'

  get 'delivery/login'

  get 'delivery/store'
  get 'delivery/cannotfind'

  get 'delivery/Tracking'
  post 'delivery/store'

  get 'delivery/about_us'

  root 'delivery#homepage'

  resources :customers

end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  validates_presence_of :s_ID
  validates_presence_of :i_ID
  validates_numericality_of :s_ID
  validates_uniqueness_of :s_ID
  validates_length_of :s_ID, maximum: 7
end

app/models/carry.rb
class Carry < ActiveRecord::Base
  self.primary_key = :pkg_id
  has_many :routes, class_name: "Route", :foreign_key => "route_id", :primary_key => "rut_id"

end

app/models/courier.rb
class Courier < ActiveRecord::Base
  self.primary_key = :courier_id
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_one :user
  has_many :sendPackages, class_name: "Package", foreign_key: "sender_id"
  has_many :receivePackages, class_name: "Package", foreign_key: "receiver_id"
end

app/models/deliver.rb
class Deliver < ActiveRecord::Base
end

app/models/hold.rb
class Hold < ActiveRecord::Base
  self.primary_key = :pkg_id
end

app/models/instance.rb
class Instance < ActiveRecord::Base
  self.primary_key = :instance_id
  #belongs_to :route, class_name: "Route", foreign_key: "route_id", primary_key: "route_id"
end

app/models/package.rb
class Package < ActiveRecord::Base
  has_many :carries, class_name: "Carry", foreign_key: "pkg_id",primary_key: "package_id"
end

app/models/route.rb
class Route < ActiveRecord::Base

  has_many :instances, class_name: "Instance", foreign_key: "route_id", primary_key: "route_id"
  has_one :dept_store, class_name: "Store", foreign_key: "store_id", primary_key: "dept"
  has_one :arvl_store, class_name: "Store", foreign_key: "store_id", primary_key: "arvl"
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_one :store_add, class_name: "StoreAdd", foreign_key: "s_id", primary_key: "store_id"
end

app/models/store_add.rb
class StoreAdd < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
  has_one :store, class_name: "Store", foreign_key: "store_id", primary_key: "store_id"
end

app/controllers/carries_controller.rb
class CarriesController < ApplicationController
  before_action :set_carry, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /carries
  # GET /carries.json
  def index
    @carries = Carry.all
  end

  # GET /carries/1
  # GET /carries/1.json
  def show
  end

  # GET /carries/new
  def new
    @carry = Carry.new
  end

  # GET /carries/1/edit
  def edit
  end

  # POST /carries
  # POST /carries.json
  def create
    @carry = Carry.new(carry_params)

    respond_to do |format|
      if @carry.save
        format.html { redirect_to @carry, notice: 'Carry was successfully created.' }
        format.json { render :show, status: :created, location: @carry }
      else
        format.html { render :new }
        format.json { render json: @carry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carries/1
  # PATCH/PUT /carries/1.json
  def update
    respond_to do |format|
      if @carry.update(carry_params)
        format.html { redirect_to @carry, notice: 'Carry was successfully updated.' }
        format.json { render :show, status: :ok, location: @carry }
      else
        format.html { render :edit }
        format.json { render json: @carry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carries/1
  # DELETE /carries/1.json
  def destroy
    @carry.destroy
    respond_to do |format|
      format.html { redirect_to carries_url, notice: 'Carry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carry
      @carry = Carry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carry_params
      params.require(:carry).permit(:pkg_id, :rut_id, :ins_id)
    end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/helpers/carries_helper.rb
module CarriesHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/delivers_helper.rb
module DeliversHelper
end

app/helpers/delivery_helper.rb
module DeliveryHelper
end

app/helpers/holds_helper.rb
module HoldsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/carries/_form.html.erb
<%= form_for(@carry) do |f| %>
  <% if @carry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carry.errors.count, "error") %> prohibited this carry from being saved:</h2>

      <ul>
      <% @carry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pkg_id %><br>
    <%= f.number_field :pkg_id %>
  </div>
  <div class="field">
    <%= f.label :rut_id %><br>
    <%= f.number_field :rut_id %>
  </div>
  <div class="field">
    <%= f.label :ins_id %><br>
    <%= f.text_field :ins_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carries/edit.html.erb
<h1>Editing Carry</h1>

<%= render 'form' %>

<%= link_to 'Show', @carry %> |
<%= link_to 'Back', carries_path %>

app/views/carries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carries</h1>

<table>
  <thead>
    <tr>
      <th>Pkg</th>
      <th>Rut</th>
      <th>Ins</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carries.each do |carry| %>
      <tr>
        <td><%= carry.pkg_id %></td>
        <td><%= carry.rut_id %></td>
        <td><%= carry.ins_id %></td>
        <td><%= link_to 'Show', carry %></td>
        <td><%= link_to 'Edit', edit_carry_path(carry) %></td>
        <td><%= link_to 'Destroy', carry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carry', new_carry_path %>

app/views/carries/new.html.erb
<h1>New Carry</h1>

<%= render 'form' %>

<%= link_to 'Back', carries_path %>

app/views/carries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pkg:</strong>
  <%= @carry.pkg_id %>
</p>

<p>
  <strong>Rut:</strong>
  <%= @carry.rut_id %>
</p>

<p>
  <strong>Ins:</strong>
  <%= @carry.ins_id %>
</p>

<%= link_to 'Edit', edit_carry_path(@carry) %> |
<%= link_to 'Back', carries_path %>