config/routes.rb
Rails.application.routes.draw do
  resources :instances
  resources :zipcodes
  resources :store_adds
  resources :routes
  resources :holds
  resources :customer_adds
  resources :carries
  resources :couriers
  resources :delivers
  resources :packages
  resources :customers
  resources :stores
  devise_for :users
  devise_scope :user do
    authenticated :user do
       root :to => 'customers#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'delivery#homepage', as: :unauthenticated_root
    end
  end
  resources :advisors
  post 'delivery/Tracking'
  get 'delivery/homepage'

  get 'delivery/login'

  get 'delivery/store'
  get 'delivery/cannotfind'

  get 'delivery/Tracking'
  post 'delivery/store'

  get 'delivery/about_us'

  root 'delivery#homepage'

  resources :customers

end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  validates_presence_of :s_ID
  validates_presence_of :i_ID
  validates_numericality_of :s_ID
  validates_uniqueness_of :s_ID
  validates_length_of :s_ID, maximum: 7
end

app/models/carry.rb
class Carry < ActiveRecord::Base
  self.primary_key = :pkg_id
  has_many :routes, class_name: "Route", :foreign_key => "route_id", :primary_key => "rut_id"

end

app/models/courier.rb
class Courier < ActiveRecord::Base
  self.primary_key = :courier_id
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_one :user
  has_many :sendPackages, class_name: "Package", foreign_key: "sender_id"
  has_many :receivePackages, class_name: "Package", foreign_key: "receiver_id"
end

app/models/deliver.rb
class Deliver < ActiveRecord::Base
end

app/models/hold.rb
class Hold < ActiveRecord::Base
  self.primary_key = :pkg_id
end

app/models/instance.rb
class Instance < ActiveRecord::Base
  self.primary_key = :instance_id
  #belongs_to :route, class_name: "Route", foreign_key: "route_id", primary_key: "route_id"
end

app/models/package.rb
class Package < ActiveRecord::Base
  has_many :carries, class_name: "Carry", foreign_key: "pkg_id",primary_key: "package_id"
end

app/models/route.rb
class Route < ActiveRecord::Base

  has_many :instances, class_name: "Instance", foreign_key: "route_id", primary_key: "route_id"
  has_one :dept_store, class_name: "Store", foreign_key: "store_id", primary_key: "dept"
  has_one :arvl_store, class_name: "Store", foreign_key: "store_id", primary_key: "arvl"
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_one :store_add, class_name: "StoreAdd", foreign_key: "s_id", primary_key: "store_id"
end

app/models/store_add.rb
class StoreAdd < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
  has_one :store, class_name: "Store", foreign_key: "store_id", primary_key: "store_id"
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:store_id, :store_name, :store_level, :phone, :supervisor)
    end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/helpers/carries_helper.rb
module CarriesHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/delivers_helper.rb
module DeliversHelper
end

app/helpers/delivery_helper.rb
module DeliveryHelper
end

app/helpers/holds_helper.rb
module HoldsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :store_id %><br>
    <%= f.text_field :store_id %>
  </div>
  <div class="field">
    <%= f.label :store_name %><br>
    <%= f.text_field :store_name %>
  </div>
  <div class="field">
    <%= f.label :store_level %><br>
    <%= f.number_field :store_level %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :supervisor %><br>
    <%= f.text_field :supervisor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stores</h1>

<table>
  <thead>
    <tr>
      <th>Store</th>
      <th>Store name</th>
      <th>Store level</th>
      <th>Phone</th>
      <th>Supervisor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each  do |store| %>
      <tr>
        <td><%= store.store_id %></td>
        <td><%= store.store_name %></td>
        <td><%= store.store_level %></td>
        <td><%= store.phone %></td>
        <td><%= store.supervisor %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Store:</strong>
  <%= @store.store_id %>
</p>

<p>
  <strong>Store name:</strong>
  <%= @store.store_name %>
</p>

<p>
  <strong>Store level:</strong>
  <%= @store.store_level %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @store.phone %>
</p>

<p>
  <strong>Supervisor:</strong>
  <%= @store.supervisor %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>