config/routes.rb
Rails.application.routes.draw do
  resources :instances
  resources :zipcodes
  resources :store_adds
  resources :routes
  resources :holds
  resources :customer_adds
  resources :carries
  resources :couriers
  resources :delivers
  resources :packages
  resources :customers
  resources :stores
  devise_for :users
  devise_scope :user do
    authenticated :user do
       root :to => 'customers#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'delivery#homepage', as: :unauthenticated_root
    end
  end
  resources :advisors
  post 'delivery/Tracking'
  get 'delivery/homepage'

  get 'delivery/login'

  get 'delivery/store'
  get 'delivery/cannotfind'

  get 'delivery/Tracking'
  post 'delivery/store'

  get 'delivery/about_us'

  root 'delivery#homepage'

  resources :customers

end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  validates_presence_of :s_ID
  validates_presence_of :i_ID
  validates_numericality_of :s_ID
  validates_uniqueness_of :s_ID
  validates_length_of :s_ID, maximum: 7
end

app/models/carry.rb
class Carry < ActiveRecord::Base
  self.primary_key = :pkg_id
  has_many :routes, class_name: "Route", :foreign_key => "route_id", :primary_key => "rut_id"

end

app/models/courier.rb
class Courier < ActiveRecord::Base
  self.primary_key = :courier_id
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_one :user
  has_many :sendPackages, class_name: "Package", foreign_key: "sender_id"
  has_many :receivePackages, class_name: "Package", foreign_key: "receiver_id"
end

app/models/deliver.rb
class Deliver < ActiveRecord::Base
end

app/models/hold.rb
class Hold < ActiveRecord::Base
  self.primary_key = :pkg_id
end

app/models/instance.rb
class Instance < ActiveRecord::Base
  self.primary_key = :instance_id
  #belongs_to :route, class_name: "Route", foreign_key: "route_id", primary_key: "route_id"
end

app/models/package.rb
class Package < ActiveRecord::Base
  has_many :carries, class_name: "Carry", foreign_key: "pkg_id",primary_key: "package_id"
end

app/models/route.rb
class Route < ActiveRecord::Base

  has_many :instances, class_name: "Instance", foreign_key: "route_id", primary_key: "route_id"
  has_one :dept_store, class_name: "Store", foreign_key: "store_id", primary_key: "dept"
  has_one :arvl_store, class_name: "Store", foreign_key: "store_id", primary_key: "arvl"
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_one :store_add, class_name: "StoreAdd", foreign_key: "s_id", primary_key: "store_id"
end

app/models/store_add.rb
class StoreAdd < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
  has_one :store, class_name: "Store", foreign_key: "store_id", primary_key: "store_id"
end

app/controllers/holds_controller.rb
class HoldsController < ApplicationController
  before_action :set_hold, only: [:show, :edit, :update, :destroy]

  # GET /holds
  # GET /holds.json
  def index
    @holds = Hold.all
  end

  # GET /holds/1
  # GET /holds/1.json
  def show
  end

  # GET /holds/new
  def new
    @hold = Hold.new
  end

  # GET /holds/1/edit
  def edit
  end

  # POST /holds
  # POST /holds.json
  def create
    @hold = Hold.new(hold_params)

    respond_to do |format|
      if @hold.save
        format.html { redirect_to @hold, notice: 'Hold was successfully created.' }
        format.json { render :show, status: :created, location: @hold }
      else
        format.html { render :new }
        format.json { render json: @hold.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holds/1
  # PATCH/PUT /holds/1.json
  def update
    respond_to do |format|
      if @hold.update(hold_params)
        format.html { redirect_to @hold, notice: 'Hold was successfully updated.' }
        format.json { render :show, status: :ok, location: @hold }
      else
        format.html { render :edit }
        format.json { render json: @hold.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holds/1
  # DELETE /holds/1.json
  def destroy
    @hold.destroy
    respond_to do |format|
      format.html { redirect_to holds_url, notice: 'Hold was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hold
      @hold = Hold.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hold_params
      params.require(:hold).permit(:pkg_id, :sto_id)
    end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/helpers/carries_helper.rb
module CarriesHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/delivers_helper.rb
module DeliversHelper
end

app/helpers/delivery_helper.rb
module DeliveryHelper
end

app/helpers/holds_helper.rb
module HoldsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/holds/_form.html.erb
<%= form_for(@hold) do |f| %>
  <% if @hold.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hold.errors.count, "error") %> prohibited this hold from being saved:</h2>

      <ul>
      <% @hold.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pkg_id %><br>
    <%= f.text_field :pkg_id %>
  </div>
  <div class="field">
    <%= f.label :sto_id %><br>
    <%= f.number_field :sto_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/holds/edit.html.erb
<h1>Editing Hold</h1>

<%= render 'form' %>

<%= link_to 'Show', @hold %> |
<%= link_to 'Back', holds_path %>

app/views/holds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Holds</h1>

<table>
  <thead>
    <tr>
      <th>Pkg</th>
      <th>Sto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @holds.each do |hold| %>
      <tr>
        <td><%= hold.pkg_id %></td>
        <td><%= hold.sto_id %></td>
        <td><%= link_to 'Show', hold %></td>
        <td><%= link_to 'Edit', edit_hold_path(hold) %></td>
        <td><%= link_to 'Destroy', hold, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hold', new_hold_path %>

app/views/holds/new.html.erb
<h1>New Hold</h1>

<%= render 'form' %>

<%= link_to 'Back', holds_path %>

app/views/holds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pkg:</strong>
  <%= @hold.pkg_id %>
</p>

<p>
  <strong>Sto:</strong>
  <%= @hold.sto_id %>
</p>

<%= link_to 'Edit', edit_hold_path(@hold) %> |
<%= link_to 'Back', holds_path %>