config/routes.rb
Rails.application.routes.draw do
  resources :instances
  resources :zipcodes
  resources :store_adds
  resources :routes
  resources :holds
  resources :customer_adds
  resources :carries
  resources :couriers
  resources :delivers
  resources :packages
  resources :customers
  resources :stores
  devise_for :users
  devise_scope :user do
    authenticated :user do
       root :to => 'customers#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'delivery#homepage', as: :unauthenticated_root
    end
  end
  resources :advisors
  post 'delivery/Tracking'
  get 'delivery/homepage'

  get 'delivery/login'

  get 'delivery/store'
  get 'delivery/cannotfind'

  get 'delivery/Tracking'
  post 'delivery/store'

  get 'delivery/about_us'

  root 'delivery#homepage'

  resources :customers

end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  validates_presence_of :s_ID
  validates_presence_of :i_ID
  validates_numericality_of :s_ID
  validates_uniqueness_of :s_ID
  validates_length_of :s_ID, maximum: 7
end

app/models/carry.rb
class Carry < ActiveRecord::Base
  self.primary_key = :pkg_id
  has_many :routes, class_name: "Route", :foreign_key => "route_id", :primary_key => "rut_id"

end

app/models/courier.rb
class Courier < ActiveRecord::Base
  self.primary_key = :courier_id
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_one :user
  has_many :sendPackages, class_name: "Package", foreign_key: "sender_id"
  has_many :receivePackages, class_name: "Package", foreign_key: "receiver_id"
end

app/models/deliver.rb
class Deliver < ActiveRecord::Base
end

app/models/hold.rb
class Hold < ActiveRecord::Base
  self.primary_key = :pkg_id
end

app/models/instance.rb
class Instance < ActiveRecord::Base
  self.primary_key = :instance_id
  #belongs_to :route, class_name: "Route", foreign_key: "route_id", primary_key: "route_id"
end

app/models/package.rb
class Package < ActiveRecord::Base
  has_many :carries, class_name: "Carry", foreign_key: "pkg_id",primary_key: "package_id"
end

app/models/route.rb
class Route < ActiveRecord::Base

  has_many :instances, class_name: "Instance", foreign_key: "route_id", primary_key: "route_id"
  has_one :dept_store, class_name: "Store", foreign_key: "store_id", primary_key: "dept"
  has_one :arvl_store, class_name: "Store", foreign_key: "store_id", primary_key: "arvl"
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_one :store_add, class_name: "StoreAdd", foreign_key: "s_id", primary_key: "store_id"
end

app/models/store_add.rb
class StoreAdd < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
  has_one :store, class_name: "Store", foreign_key: "store_id", primary_key: "store_id"
end

app/controllers/advisors_controller.rb
class AdvisorsController < ApplicationController
  before_action :set_advisor, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /advisors
  # GET /advisors.json
  def index
    @advisors = Advisor.all
  end

  # GET /advisors/1
  # GET /advisors/1.json
  def show
  end

  # GET /advisors/new
  def new
    @advisor = Advisor.new
  end

  # GET /advisors/1/edit
  def edit
  end

  # POST /advisors
  # POST /advisors.json
  def create
    @advisor = Advisor.new(advisor_params)

    respond_to do |format|
      if @advisor.save
        format.html { redirect_to @advisor, notice: 'Advisor was successfully created.' }
        format.json { render :show, status: :created, location: @advisor }
      else
        format.html { render :new }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advisors/1
  # PATCH/PUT /advisors/1.json
  def update
    respond_to do |format|

      if @advisor.update(advisor_params)
        format.html { redirect_to @advisor, notice: 'Advisor was successfully updated.' }
        format.json { render :show, status: :ok, location: @advisor }
      else
        format.html { render :edit }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advisors/1
  # DELETE /advisors/1.json
  def destroy
    @advisor.destroy
    respond_to do |format|
      format.html { redirect_to advisors_url, notice: 'Advisor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advisor
      @advisor = Advisor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advisor_params
      params.require(:advisor).permit(:s_ID, :i_ID)
    end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/helpers/carries_helper.rb
module CarriesHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/delivers_helper.rb
module DeliversHelper
end

app/helpers/delivery_helper.rb
module DeliveryHelper
end

app/helpers/holds_helper.rb
module HoldsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/advisors/_form.html.erb
<%= form_for(@advisor) do |f| %>
  <% if @advisor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advisor.errors.count, "error") %> prohibited this advisor from being saved:</h2>

      <ul>
      <% @advisor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :s_ID %><br>
    <%= f.text_field :s_ID %>
  </div>
  <div class="field">
    <%= f.label :i_ID %><br>
    <%= f.text_field :i_ID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advisors/edit.html.erb
<h1>Editing Advisor</h1>

<%= render 'form' %>

<%= link_to 'Show', @advisor %> |
<%= link_to 'Back', advisors_path %>

app/views/advisors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Advisors</h1>

<table>
  <thead>
    <tr>
      <th>S id</th>
      <th>I id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advisors.each do |advisor| %>
      <tr>
        <td><%= advisor.s_ID %></td>
        <td><%= advisor.i_ID %></td>
        <td><%= link_to 'Show', advisor %></td>
        <td><%= link_to 'Edit', edit_advisor_path(advisor) %></td>
        <td><%= link_to 'Destroy', advisor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advisor', new_advisor_path %>

app/views/advisors/new.html.erb
<h1>New Advisor</h1>

<%= render 'form' %>

<%= link_to 'Back', advisors_path %>

app/views/advisors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>S id:</strong>
  <%= @advisor.s_ID %>
</p>

<p>
  <strong>I id:</strong>
  <%= @advisor.i_ID %>
</p>

<%= link_to 'Edit', edit_advisor_path(@advisor) %> |
<%= link_to 'Back', advisors_path %>